---

rhbase_firewall_allow_services:
  - http
  - https
rhbase_firewall_allow_ports:
  - 53/tcp
  - 53/udp

httpd_server_name: "{{ ansible_hostname }}"

mariadb_databases:
  - name: wordpress

mariadb_users:
  - name: fpkmatthi
    password: "{{ vault_mariadb_fpkmatthi_pw }}"
    priv: 'wordpress.*:ALL'

mariadb_root_password: "{{ vault_mariadb_root_pw }}"

wordpress_database: wordpress
wordpress_user: fpkmatthi
wordpress_password: "{{ vault_wp_fpkmatthi_pw }}"
