# web.yml
---

- hosts: web
  become: true
  roles:
    - bertvv.rh-base
    - sepolicy
    - bertvv.httpd
    - bertvv.mariadb
    - bertvv.wordpress
    - phpmyadmin
    - hwwilliams.fail2ban
    - resolv.conf
    - default.gw
  tasks:
    - name: Install Cockpit
      package:
        name:
          - cockpit
          - cockpit-dashboard
    - name: Ensure Cockpit is running
      service:
        name: cockpit.socket
        state: started
        enabled: true
    - name: Allow traffic to Cockpit dashboard through the firewall
      firewalld:
        port: 9090/tcp
        state: enabled
        permanent: true
